### ISSUE TITLE
minipax does not check if file exists with   -r -f foo.tar

### ISSUE THREAD

**Issue by jocelyn** [ntruessel/etar#56]
when trying to extract foo.tar ... I do

minipax -r -f foo.tar

but if foo.tar does not exists ... the execution violates assertions, it is missing a simple file existence checking .. and appropriate error message.

This is minor issue for the example, but could be annoying for a tool.

**Comment by ntruessel** [comment]
Assertion violation was caused by wrong assertion. There are still no appropriate error messages.

**Comment by ntruessel** [comment]
Errors now are printed to stderr.
